# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error prevention
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style consistency
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true

    # Readability
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_positional_boolean_parameters: true
    avoid_returning_this: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    # cascade_invocations: false  # Disabled - many false positives (e.g., calloc.free chains)
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    prefer_asserts_in_initializer_lists: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_string_buffers: true

    # Type safety
    always_declare_return_types: true
    avoid_dynamic_calls: true

    # Disabled for now (would require significant refactoring)
    # public_member_api_docs: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
